version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["poetry", "run", "uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000"]

  # database:
  #   image: postgres:18-alpine
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: intellegent_image
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: